services:
  neo4j:
    container_name: neo4j
    image: neo4j:enterprise
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
     